#!/bin/bash
dayback=30
LAST_JOB=`qstat -a | tail -1 | awk -F. '{print $1}'`
OUTPUT="log_28"
echo "JOBID QUEUE QUEUE_TIME RUN_TIME USER" > $OUTPUT

total=0
qtime=0
qstat -r | grep " R " > list
while read line; do
  ii=`echo $line | awk -F. '{print $1}'`
  user=`echo $line | awk '{print $2}'`
  queue=`echo $line | awk '{print $3}'`
  hour=`echo $line | awk '{print $11}' | awk -F: '{print $1}'`
  min=`echo $line | awk '{print $11}' | awk -F: '{print $2}'`
  rtime=`echo "scale=2; $hour + $min / 60" | bc -l`
  total=`echo "scale=1; $total + $rtime" | bc -l`
  echo "$ii $queue $qtime $rtime $user" >> $OUTPUT
done < list
rm list
echo "Currently Running: $total hrs"

# Earliest: 510
# Earliest: 3838 2022.2.8
# Earliest: 10225 2022.6.15
# Earliest: 21048 2022.12.23
# Earliest: 26315 2023.4.17
for ii in $(seq 26315 $LAST_JOB); do 
  check=`tracejob $ii -n $dayback -slmq | grep resources_used.walltime`
  if [[ "${check}" ]]; then
    hour=`tracejob $ii -n $dayback -slmq | grep resources_used.walltime | sed -n -e 's/.*resources_used.walltime=//p' | awk '{print $1}' | awk -F: '{print $1}'`
    min=`tracejob $ii -n $dayback -slmq | grep resources_used.walltime | sed -n -e 's/.*resources_used.walltime=//p' | awk '{print $1}' | awk -F: '{print $2}'`
    rtime=`echo "scale=1; $hour + $min / 60" | bc -l`
    if (( $(echo "$rtime < 1" | bc -l) )); then
      continue
    else
      queue=`tracejob $ii -n $dayback -slmq | grep queue | head -1 | sed -n -e 's/.*queue=//p' | awk '{print $1}'`
      user=`tracejob $ii -n $dayback -slmq | grep user | head -1 | sed -n -e 's/.*user=//p' | awk '{print $1}'`
      A=`tracejob $ii -n $dayback -slmq | grep qtime | head -1 | sed -n -e 's/.*qtime=//p' | awk '{print $1}'`
      B=`tracejob $ii -n $dayback -slmq | grep start | head -1 | sed -n -e 's/.*start=//p' | awk '{print $1}'`
      qtime=`echo "scale=1; ($B - $A)/3600" | bc -l`
      echo "$ii $queue $qtime $rtime $user" >> $OUTPUT
    fi
  else
    continue
  fi
done

