#!/bin/zsh

cat > iplist <<EOF
6
13
14
24
63
80
81
85
88
89
223
233
25
50
188
55

64
65
66
70
56

57
58
59
60
61
62

209
210
211
EOF

echo -e "# 'Login in Past 3 days'\t'Changes in 24 hrs'\t'Suspecious Running'"
echo -e "# 'Success/Total'\t\tbin\tsbin"
for ii in `cat iplist`; do 
    echo -n $ii
    #ssh zju$ii "grep -v "^#" ~/log"
    ssh root@zju$ii "./watcher" > tmp$ii
    grep -v "^#" tmp$ii
done
rm iplist tmp*
